version: '3'

services:
  db:
    container_name: sql1
    hostname: sql1
    build:
      context: ./sqlserver
      dockerfile: Dockerfile
    ports:
      - "1433:1433"
    environment:
      MSSQL_SA_PASSWORD: "r00t.R00T" #user=sa
      ACCEPT_EULA: "Y"
      MSSQL_DATA_DIR: /var/opt/mssql/data
      MSSQL_PID: 'Developer' #specifies the freely licensed Developer Edition of SQL Server for non-production use
      MSSQL_TCP_PORT: 1433
    volumes:
      - ./_sqlserver/data:/var/opt/mssql/data
      - ./_sqlserver/secrets:/var/opt/mssql/secrets
      - ./_sqlserver/log:/var/opt/mssql/log
    #healthcheck:
    #  test: sqlcmd -S db1.internal.prod.example.com -U SA -P 'Alaska2017' -Q 'select distinct 1 from AdventureWorksDW2017.dbo.DimDate'

  adminer:
    build:
      context: ./adminer
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    links:
      - db
