version: '3'

services:
  postgres:
    image:
      postgres:12.2-alpine
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
      DB_PORT: '5432'
      DB_HOST: '172.17.0.1'
    ports:
      - 5432:5432
    volumes:
      - ./_postgres/data:/var/lib/postgresql/data
      - ./indexer-schema.sql:/docker-entrypoint-initdb.d/init.sql
    restart:
      unless-stopped
    network_mode: 'host'

  adminer:
    image: adminer:4.7.6
    restart: unless-stopped
    ports:
      - 8080:8080
    network_mode: 'host'
